name: lepton
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cairo=1.18.2
  - contourpy=1.3.1
  - cycler=0.12.1
  - double-conversion=3.3.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.56.0
  - freetype=2.12.1
  - git=2.48.1
  - graphite2=1.3.13
  - harfbuzz=10.4.0
  - icu=75.1
  - intel-openmp=2024.2.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=19.1.7
  - libdeflate=1.23
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libglib=2.82.2
  - libgomp=14.2.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libmpdec=4.0.0
  - libpng=1.6.47
  - libsqlite=3.49.1
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.6
  - libxslt=1.1.39
  - libzlib=1.3.1
  - matplotlib=3.10.1
  - matplotlib-base=3.10.1
  - mkl=2024.2.2
  - munkres=1.1.4
  - numpy=2.2.3
  - openjpeg=2.5.3
  - openssl=3.4.1
  - packaging=24.2
  - pcre2=10.44
  - pillow=11.1.0
  - pip=25.0.1
  - pixman=0.44.2
  - pthread-stubs=0.4
  - pyparsing=3.2.1
  - pyside6=6.8.2
  - python=3.13.2
  - python-dateutil=2.9.0.post0
  - python_abi=3.13
  - qhull=2020.2
  - qt6-main=6.8.2
  - scipy=1.15.2
  - six=1.17.0
  - tbb=2021.13.0
  - tk=8.6.13
  - tornado=6.4.2
  - tzdata=2025a
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zstd=1.5.7
  - pip:
      - opencv-python==4.11.0.86
      - pyav==14.2.1

