name: lepton
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - contourpy=1.3.1
  - cycler=0.11.0
  - expat=2.6.4
  - fonttools=4.55.3
  - freetype=2.12.1
  - git=2.45.2
  - icu=73.1
  - intel-openmp=2023.1.0
  - jpeg=9e
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.22
  - libffi=3.4.4
  - libmpdec=4.0.0
  - libpng=1.6.39
  - libpq=17.2
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - numpy=2.2.2
  - numpy-base=2.2.2
  - openjpeg=2.5.2
  - openssl=3.0.15
  - packaging=24.2
  - pillow=11.1.0
  - pip=25.0
  - ply=3.11
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.13.2
  - python-dateutil=2.9.0post0
  - python_abi=3.13
  - qt-main=5.15.2
  - setuptools=72.1.0
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tornado=6.4.2
  - tzdata=2025a
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - opencv-python==4.11.0.86
      - pyav==14.2.1
