[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lepton-pt"
dynamic = ["version"]
description = "Runs a FLIR Lepton 3.5 on a Purethermal3 in Windows."
requires-python = ">=3.12"
license = "GPL-3.0-only"
license-files = ["COPYING", ]
readme = "README.md"
keywords = [
    "FLIR",
    "lepton",
    "purethermal",
    "thermal camera",
    "windows",
]
authors = [{ name = "Grayson Schaer", email = "gschaer2@illinois.edu" }]
maintainers = [{ name = "Grayson Schaer", email = "gschaer2@illinois.edu" }]
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 5 - Production/Stable",
    "Natural Language :: English",
    "Operating System :: Microsoft :: Windows",]
dependencies = [
    "numpy",
    "matplotlib",
    "opencv-python",
    "scikit-image",
]

[project.optional-dependencies]
dev = [
   "spyder",
   "notebook",
   "twine",
   "build",
   "sphinx",
   "sphinx-collections",
   "numpydoc",
   "autoclasstoc",
   "sphinx-rtd-theme",
   "nbsphinx",
]

[project.urls]
"Homepage" = "https://grayks3248.github.io/Lepton3.5_Purethermal3/"
"Bug Reports" = "https://github.com/GrayKS3248/Lepton3.5_Purethermal3/issues/"
"Source" = "https://github.com/GrayKS3248/Lepton3.5_Purethermal3/"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
version = {attr = "lepton.__version__"}

[project.scripts]
leprun = "lepton:leprun"
