[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lepton-pt"
dynamic = ["version"]
description = "Runs a FLIR Lepton 3.5 on a Purethermal3 in Windows."
requires-python = ">=3.12"
license = "GPL-3.0-only AND MIT"
license-files = ["COPYING",]
keywords = [
    "FLIR",
    "lepton",
    "purethermal",
    "thermal camera",
    "windows",
]
authors = [{ name = "Grayson Schaer", email = "gschaer2@illinois.edu" }]
maintainers = [{ name = "Grayson Schaer", email = "gschaer2@illinois.edu" }]
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 5 - Production/Stable",
    "Natural Language :: English",
    "Operating System :: Microsoft :: Windows",]
dependencies = [
    "numpy",
    "matplotlib",
    "opencv-python",
    "scikit-image",
]

[project.optional-dependencies]
dev = [
   "spyder",
   "twine",
   "build",
   "sphinx",
   "sphinx-collections",
   "numpydoc",
   "autoclasstoc",
   "sphinx-rtd-theme",
   "nbsphinx",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
version = {attr = "lepton.__version__"}

[project.scripts]
leprun = "lepton:leprun"
